{{/*
ConfigMap - Variables de configuration de l'application
Ces valeurs sont injectees comme variables d'environnement dans les pods
*/}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "stock-prediction.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "stock-prediction.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
