{{/*
Deployment - Deploie les pods de l'API
C'est le fichier le plus important du chart !
*/}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "stock-prediction.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "stock-prediction.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "stock-prediction.selectorLabels" . | nindent 6 }}
  # Strategie de mise a jour (zero-downtime)
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        {{- include "stock-prediction.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        # Force le redemarrage si la ConfigMap change
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: api
          image: {{ include "stock-prediction.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
          # Variables d'environnement depuis la ConfigMap
          envFrom:
            - configMapRef:
                name: {{ include "stock-prediction.fullname" . }}-config
          # Ressources CPU/Memoire
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          # Health check : le pod est-il vivant ?
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: {{ .Values.livenessProbe.port }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          # Health check : le pod est-il pret a recevoir du trafic ?
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: {{ .Values.readinessProbe.port }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
