{{/*
Service - Expose l'API aux autres pods du cluster
Le Service agit comme un load-balancer interne
*/}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "stock-prediction.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "stock-prediction.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "stock-prediction.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
